export type ProjectStatus = "shipped" | "in-progress" | "archived"

export interface ProjectDetailSection {
  title: string
  body: string
}

export interface ProjectPolicySection {
  heading: string
  points: string[]
}

export interface Project {
  id: number
  slug: string
  title: string
  description: string
  tags: string[]
  status: ProjectStatus
  year: string
  stars: number
  forks: number
  url: string
  homepage: string | null
  featured: boolean
  highlight: boolean
  summary: string
  details: ProjectDetailSection[]
  terms: ProjectPolicySection[]
  privacy: ProjectPolicySection[]
  legalTerms?: ProjectPolicySection[]
  legalPrivacy?: ProjectPolicySection[]
  effectiveDate?: string
}

const standardTerms = (projectName: string): ProjectPolicySection[] => [
  {
    heading: "Use of the project",
    points: [
      `${projectName} is provided as an open-source or personal project artifact for learning, experimentation, and practical reuse where its repository license allows it.`,
      "You are responsible for reviewing the source, dependencies, configuration, and deployment environment before using it in production or sensitive workflows.",
      "The project may change, pause, or be archived without prior notice because it is maintained as part of an independent workshop rather than a commercial service.",
    ],
  },
  {
    heading: "No warranty",
    points: [
      "The software and documentation are provided as-is, without guarantees of uptime, compatibility, data recovery, or fitness for a specific purpose.",
      "Any automation, system command, school, home, or government-office workflow should be tested in a safe environment before real-world use.",
    ],
  },
  {
    heading: "Contributions and attribution",
    points: [
      "Issues, forks, and pull requests are welcome when the repository is active and public contribution is practical.",
      "Please preserve relevant copyright notices, license text, and attribution when adapting the work.",
    ],
  },
]

const standardPrivacy = (projectName: string): ProjectPolicySection[] => [
  {
    heading: "Project page analytics",
    points: [
      `This ${projectName} detail page may be measured through the site's privacy-conscious analytics setup to understand page visits and performance.`,
      "No account registration, newsletter signup, or project-specific tracking form is required to read this page.",
    ],
  },
  {
    heading: "Repository and external links",
    points: [
      "Opening the source repository or any external homepage may send standard request information to that third-party platform.",
      "Those external services are governed by their own terms, privacy policies, cookies, and logging practices.",
    ],
  },
  {
    heading: "Local and self-hosted data",
    points: [
      "Projects intended for offline or self-hosted use keep their runtime data in the environment where you install or operate them, unless you connect external services yourself.",
      "Review configuration files, secrets, logs, and storage paths before deploying a fork with real user data.",
    ],
  },
]

const samugaaPrivacy: ProjectPolicySection[] = [
  {
    heading: "Summary",
    points: [
      "Samugaa is designed as an offline-first productivity app for notes, todos, subtasks, and work logs. The app stores your data locally on your Android device and may sync it with the Samugaa backend when you sign in and use sync features.",
      "Samugaa does not include advertising SDKs, third-party analytics SDKs, location tracking, contact access, microphone access, SMS access, or camera access in the Android app.",
    ],
  },
  {
    heading: "Information we collect",
    points: [
      "If you register or sign in, the app may send and store your email address, password for authentication, display name if provided, authentication token, and user account identifier.",
      "The app stores and may sync notes, todos, subtasks, work logs, task metadata, tags, timestamps, deletion status, due dates, priority, and linked todo identifiers.",
      "To support authentication and syncing, the app may use a device identifier, device name, platform value, sync timestamps, sync version metadata, IP address, request time, and server logs generated by the hosting provider or backend infrastructure.",
    ],
  },
  {
    heading: "Information stored locally on your device",
    points: [
      "Samugaa stores app data locally using Android Room database storage, including notes, todos, subtasks, work logs, sync metadata, and deletion markers.",
      "Session information, including your authentication token and user information, is stored using encrypted Android shared preferences.",
      "The Android app currently allows Android system backup. Depending on your device settings, operating system, and Google account backup configuration, some app data may be included in backups managed by Android or Google.",
    ],
  },
  {
    heading: "Information sent to the server",
    points: [
      "The app communicates with the Samugaa backend at https://moshradix-site.vercel.app.",
      "The app sends data to the backend when you register, sign in, or manually sync. This may include account information, device identifier, notes, todos, subtasks, work logs, and sync metadata.",
      "The backend may return synced changes from the server to your device.",
    ],
  },
  {
    heading: "App permissions",
    points: [
      "INTERNET is required to sign in, register, and sync data with the backend.",
      "ACCESS_NETWORK_STATE is used to check network availability.",
      "The app does not request permissions for precise location, approximate location, contacts, camera, microphone, SMS, call logs, calendar, Bluetooth, or nearby devices.",
    ],
  },
  {
    heading: "How we use your information",
    points: [
      "We use your information to create and manage your account, authenticate you, store your notes, todos, subtasks, and work logs, sync data, preserve offline-first functionality, resolve sync conflicts, maintain reliability and security, and diagnose technical issues.",
      "We do not use your data for advertising.",
    ],
  },
  {
    heading: "Open source nature of the app",
    points: [
      "Samugaa is open source. The application source code may be publicly available for inspection, review, modification, and redistribution under its applicable open source license.",
      "Open source availability of the code does not mean your personal app data is public.",
    ],
  },
  {
    heading: "Free use",
    points: [
      "Samugaa is provided free of charge. We do not sell access to your personal information, and we do not require payment to use the app.",
      "If paid services, hosted accounts, donations, or premium features are introduced in the future, this Privacy Policy should be updated before those changes apply.",
    ],
  },
  {
    heading: "Sharing of information",
    points: [
      "We do not sell your personal information.",
      "We may share or process information with backend hosting or infrastructure providers needed to operate the service, when required by law, to protect rights, safety, and security, or with your consent or at your direction.",
    ],
  },
  {
    heading: "Third-party services",
    points: [
      "The Android app communicates with the Samugaa backend. The backend may be hosted using third-party infrastructure providers, such as Vercel or other hosting services.",
      "Those providers may process technical information such as IP addresses, request logs, timestamps, and error logs according to their own terms and privacy practices.",
      "The Android app itself does not include third-party advertising or analytics SDKs based on the current source code.",
    ],
  },
  {
    heading: "Data retention",
    points: [
      "Local data remains on your device until you delete it, clear the app's data, uninstall the app, or remove it through app functionality.",
      "Synced data may remain on the backend until it is deleted, overwritten, or removed according to backend retention practices.",
      "Deletion markers may be retained temporarily or permanently where needed to support sync consistency across devices.",
    ],
  },
  {
    heading: "Data deletion",
    points: [
      "You may delete notes, todos, and work logs in the app where deletion functionality is available. Deleted items may be marked as deleted to support sync behavior.",
      "To request deletion of your account or synced server data, sign in at /samugaa/account-deletion and submit the authenticated request form, or contact shaamil.is@gmail.com if you cannot sign in.",
      "If you run your own backend or modified version of the app, you are responsible for the data stored in your own deployment.",
    ],
  },
  {
    heading: "Security",
    points: [
      "Samugaa uses reasonable technical measures including encrypted shared preferences for session data, local database storage for offline app data, HTTPS communication with the backend, and authentication tokens for protected sync requests.",
      "No method of storage or transmission is completely secure. You are responsible for keeping your device secure, using a strong account password, and protecting access to your device.",
    ],
  },
  {
    heading: "Children's privacy",
    points: [
      "Samugaa is not specifically directed to children under 13, or the minimum age required by applicable law in your jurisdiction.",
      "We do not knowingly collect personal information from children. If you believe a child has provided personal information through the app, contact us so we can take appropriate action.",
    ],
  },
  {
    heading: "International use",
    points: [
      "If you use Samugaa from outside the country where the backend is hosted or operated, your information may be transferred to and processed in other countries. Data protection laws in those countries may differ from the laws where you live.",
    ],
  },
  {
    heading: "Your rights",
    points: [
      "Depending on your location, you may have rights to access, correct, delete, object to, restrict, export, or withdraw consent for certain personal information processing.",
      "To exercise these rights, contact shaamil.is@gmail.com.",
    ],
  },
  {
    heading: "Changes to this Privacy Policy",
    points: [
      "This Privacy Policy may be updated from time to time. When changes are made, the effective date at the top of this document should be updated.",
      "Material changes should be communicated through the project repository, app release notes, website, or another reasonable method.",
    ],
  },
  {
    heading: "Contact",
    points: ["For privacy questions, account deletion requests, or data requests, contact Mohamed Shamil at shaamil.is@gmail.com or www.mosh-one.us."],
  },
]

const samugaaTerms: ProjectPolicySection[] = [
  {
    heading: "About Samugaa",
    points: [
      "Samugaa is a productivity application for managing notes, todos, subtasks, and work logs. The Android app is designed to work offline and may sync data with a backend service when you sign in and use sync features.",
      "Samugaa is provided as open source software. The source code may be available under the open source license included with the project repository.",
    ],
  },
  {
    heading: "Free use",
    points: [
      "Samugaa is currently provided free of charge.",
      "You are responsible for any costs charged by your device provider, internet provider, mobile carrier, hosting provider, or other third parties.",
      "We may modify, suspend, discontinue, or change the availability of the app or hosted services at any time.",
    ],
  },
  {
    heading: "Open source license",
    points: [
      "The app's source code is governed by the open source license provided in the project repository.",
      "These Terms apply to your use of the app and hosted Samugaa services. They do not limit rights granted to you under the applicable open source license.",
      "If you modify, redistribute, fork, self-host, or publish your own version of Samugaa, you are responsible for complying with the applicable license and laws.",
    ],
  },
  {
    heading: "Accounts",
    points: [
      "Some features may require an account. When creating an account, you agree to provide accurate information and to keep your login credentials secure.",
      "You are responsible for all activity that occurs under your account.",
      "We may suspend or terminate accounts that violate these Terms, abuse the service, create security risks, or are required to be removed by law.",
    ],
  },
  {
    heading: "Your content",
    points: [
      "Your Content means notes, todos, subtasks, work logs, tags, timestamps, and other information you create, upload, store, or sync using Samugaa.",
      "You retain ownership of Your Content. These Terms do not transfer ownership of Your Content to us.",
      "By using sync or hosted features, you grant us limited permission to store, process, transmit, and display Your Content only as necessary to operate, maintain, sync, secure, and improve Samugaa.",
      "You are responsible for Your Content and for ensuring that you have the right to store and process it using Samugaa.",
    ],
  },
  {
    heading: "Prohibited use",
    points: [
      "You agree not to use Samugaa or hosted Samugaa services to violate law, infringe rights, upload unlawful or malicious content, gain unauthorized access, disrupt infrastructure, introduce malware or automated abuse, or store highly sensitive information requiring specialized compliance unless expressly agreed in writing.",
    ],
  },
  {
    heading: "Hosted backend service",
    points: [
      "The Android app may communicate with a hosted backend service for authentication and syncing.",
      "Hosted services are provided on an as available basis. We do not guarantee that syncing, accounts, storage, uptime, or backend access will always be available, uninterrupted, secure, or error-free.",
      "We may impose limits, disable access, remove data, or suspend features if necessary to protect the service, comply with law, prevent abuse, or maintain system reliability.",
    ],
  },
  {
    heading: "Self-hosting and modified versions",
    points: [
      "If you self-host, modify, redistribute, or operate your own version of Samugaa, you are responsible for your own users, data, security, privacy policy, terms, legal compliance, and license obligations.",
      "You must not imply that your version is officially operated or endorsed by the original maintainers unless authorized.",
    ],
  },
  {
    heading: "Privacy",
    points: [
      "Your use of Samugaa is also governed by the Samugaa Privacy Policy, which explains what information the app collects, stores, syncs, and protects.",
    ],
  },
  {
    heading: "Data loss and backups",
    points: [
      "Samugaa is an offline-first app, but data loss may still occur due to device failure, app bugs, sync conflicts, deletion, account issues, backend outages, operating system behavior, or user error.",
      "You are responsible for maintaining backups of important information. We are not responsible for lost, corrupted, delayed, or unrecoverable data to the fullest extent permitted by law.",
    ],
  },
  {
    heading: "Security",
    points: [
      "We use reasonable measures to protect the app and hosted service, but no system is completely secure.",
      "You are responsible for keeping your device, account, password, and authentication credentials secure.",
      "If you discover a security vulnerability, please report it responsibly to shaamil.is@gmail.com.",
    ],
  },
  {
    heading: "Third-party services",
    points: [
      "Samugaa may depend on third-party platforms, libraries, hosting providers, Android services, or infrastructure providers.",
      "We are not responsible for third-party services, policies, outages, data handling, or terms.",
    ],
  },
  {
    heading: "Software updates",
    points: [
      "We may release updates, fixes, or new versions of the app. Some features may require the latest version.",
      "We are not obligated to provide updates, maintenance, support, compatibility fixes, or continued access to any particular version.",
    ],
  },
  {
    heading: "No professional advice",
    points: [
      "Samugaa is a productivity tool. It does not provide legal, financial, medical, tax, security, or professional advice.",
      "You are responsible for how you use the app and any decisions you make based on information stored in it.",
    ],
  },
  {
    heading: "Disclaimer of warranties",
    points: [
      "Samugaa is provided as is and as available.",
      "To the fullest extent permitted by law, we disclaim all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, title, non-infringement, availability, accuracy, security, and reliability.",
      "We do not warrant that the app or hosted services will be uninterrupted, error-free, secure, compatible with your device, or free from data loss.",
    ],
  },
  {
    heading: "Limitation of liability",
    points: [
      "To the fullest extent permitted by law, we will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, including loss of data, loss of profits, loss of goodwill, business interruption, device issues, or service outages.",
      "To the fullest extent permitted by law, our total liability for any claim related to Samugaa or these Terms will not exceed the greater of the amount you paid us to use Samugaa in the 12 months before the claim, or USD $0 because the app is currently provided free of charge.",
      "Some jurisdictions do not allow certain limitations of liability, so some of these limitations may not apply to you.",
    ],
  },
  {
    heading: "Indemnification",
    points: [
      "You agree to defend, indemnify, and hold harmless the Samugaa maintainers, contributors, operators, and affiliates from claims, damages, liabilities, losses, costs, and expenses arising from your use or misuse of Samugaa, Your Content, violation of these Terms, violation of law or third-party rights, or modified, redistributed, or self-hosted versions of the app or backend.",
    ],
  },
  {
    heading: "Termination",
    points: [
      "You may stop using Samugaa at any time.",
      "We may suspend or terminate your access to hosted services at any time if you violate these Terms, create risk, abuse the service, or if continued operation is no longer feasible.",
      "After termination, some provisions of these Terms will continue to apply, including ownership, disclaimers, limitation of liability, indemnification, and dispute provisions.",
    ],
  },
  {
    heading: "Changes to these Terms",
    points: [
      "We may update these Terms from time to time. When changes are made, the effective date should be updated.",
      "Continued use of Samugaa after changes become effective means you accept the updated Terms.",
    ],
  },
  {
    heading: "Governing law",
    points: [
      "These Terms are governed by applicable law, without regard to conflict of law rules. Any disputes will be handled in the appropriate court or dispute resolution forum unless applicable law requires otherwise.",
    ],
  },
  {
    heading: "Contact",
    points: ["For questions about these Terms, contact Mohamed Shamil at shaamil.is@gmail.com or www.mosh-one.us."],
  },
]

export const projects: Project[] = [
  {
    id: 8,
    slug: "samugaa-mobile-android",
    title: "Samugaa Mobile Android",
    description:
      "A native Kotlin Android rebuild of Samugaa, with Jetpack Compose Material 3, offline-first Room storage, authentication, manual sync, search, filters, and work-log capture.",
    tags: ["Kotlin", "Android", "Jetpack Compose", "Room"],
    status: "in-progress",
    year: "2026",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/samugaa-mobile-android",
    homepage: null,
    featured: true,
    highlight: true,
    effectiveDate: "June 26, 2026",
    summary:
      "Samugaa Mobile Android brings the Samugaa productivity workflow to a native Android app, keeping notes, todos, subtasks, and work logs useful offline while syncing with the MOSHRADIX backend when signed in.",
    details: [
      {
        title: "What it solves",
        body: "Samugaa gives everyday productivity data a local-first Android home. Notes, todos, subtasks, and work logs stay available on the device, while signed-in users can manually sync with the backend when the network is ready.",
      },
      {
        title: "How it is built",
        body: "The app is written in Kotlin with Jetpack Compose Material 3 for the interface, Room for offline storage, and Retrofit/OkHttp for the moshradix-site backend. It includes auth session storage, manual sync, search and filtering, and work-log capture.",
      },
      {
        title: "Current direction",
        body: "The repository is a native Android rebuild of the earlier Samugaa experience, focused on making the core productivity loop feel fast, reliable, and private enough for daily use.",
      },
    ],
    terms: [
      {
        heading: "Free open source use",
        points: [
          "Samugaa is currently provided free of charge as an open source productivity app.",
          "The app source code is governed by the license in the project repository, while hosted Samugaa services are governed by the Terms of Service.",
        ],
      },
      {
        heading: "Accounts and content",
        points: [
          "Some sync features may require an account, and you are responsible for keeping your credentials secure.",
          "You retain ownership of notes, todos, subtasks, work logs, tags, timestamps, and other content you create or sync through Samugaa.",
        ],
      },
      {
        heading: "Hosted service limits",
        points: [
          "Hosted backend services are provided as available and may be modified, suspended, limited, or discontinued when needed for reliability, security, legal compliance, or maintenance.",
          "Read the full Terms of Service for warranty, liability, self-hosting, and acceptable-use details.",
        ],
      },
    ],
    privacy: [
      {
        heading: "Offline-first data",
        points: [
          "Samugaa stores notes, todos, subtasks, work logs, sync metadata, and deletion markers locally using Android Room database storage.",
          "Session information is stored using encrypted Android shared preferences.",
        ],
      },
      {
        heading: "Sync data",
        points: [
          "When you register, sign in, or manually sync, the app may send account information, device identifiers, productivity data, and sync metadata to https://moshradix-site.vercel.app.",
          "The backend may return synced changes from the server to your device.",
        ],
      },
      {
        heading: "No ad tracking",
        points: [
          "The Android app does not include advertising SDKs, third-party analytics SDKs, location tracking, contact access, microphone access, SMS access, or camera access.",
          "Read the full Privacy Policy for retention, deletion, rights, and contact details.",
        ],
      },
    ],
    legalTerms: samugaaTerms,
    legalPrivacy: samugaaPrivacy,
  },
  {
    id: 0,
    slug: "mto-samugaa",
    title: "MTO Samugaa",
    description:
      "A bilingual (English & Dhivehi), offline-first desktop suite for Addu City Council's Municipal Technical Office - bundling document generation, task tracking, and staff logging into one fast Electron app.",
    tags: ["Electron", "JavaScript", "Offline-first", "Dhivehi i18n"],
    status: "in-progress",
    year: "2026",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/mosh-samugaa-app",
    homepage: null,
    featured: true,
    highlight: true,
    summary:
      "MTO Samugaa turns a set of repeated municipal office tasks into one local-first desktop workspace, shaped around bilingual staff workflows and unreliable connectivity.",
    details: [
      {
        title: "What it solves",
        body: "The app is designed for a technical office where forms, staff logs, task notes, and generated documents need to move quickly without waiting on cloud services. It gives the office a single place to prepare repeatable paperwork and keep operational context close to the people doing the work.",
      },
      {
        title: "How it is built",
        body: "Electron provides the desktop shell, while the interface focuses on fast local interactions, predictable templates, and Dhivehi-friendly text handling. The offline-first direction keeps the system useful on ordinary office machines and allows documents to be produced even when the network is having a bad day.",
      },
      {
        title: "Current direction",
        body: "The project is still active, with attention on template auto-computation, date handling, bilingual polish, and the small details that make an internal tool feel trustworthy for everyday staff use.",
      },
    ],
    terms: standardTerms("MTO Samugaa"),
    privacy: standardPrivacy("MTO Samugaa"),
  },
  {
    id: 1,
    slug: "quantumone",
    title: "QuantumOne",
    description:
      "An Alexa-powered web service that lets you control a Windows PC by voice - shut it down, wake it up, or run quick commands from across the room.",
    tags: ["JavaScript", "Alexa Skills", "Home Automation"],
    status: "shipped",
    year: "2019",
    stars: 1,
    forks: 0,
    url: "https://github.com/MoshRadix/QuantumOne",
    homepage: null,
    featured: true,
    highlight: false,
    summary:
      "QuantumOne connects voice commands to desktop control, exploring the practical edge between smart speakers, home automation, and a Windows machine.",
    details: [
      {
        title: "What it solves",
        body: "The project gives a voice-first route for simple PC actions that normally require walking over to the machine. It is the sort of home automation bridge that makes sense when the computer is part workstation, part media device, and part always-on household utility.",
      },
      {
        title: "How it is built",
        body: "The service uses JavaScript and an Alexa Skill flow to interpret commands, pass them to a local or reachable endpoint, and trigger actions on Windows. The interesting part is not a huge interface, but the careful handshake between cloud voice intent and local machine behavior.",
      },
      {
        title: "Current direction",
        body: "QuantumOne is shipped as an older experiment. It remains useful as a reference for voice-command plumbing and the security questions that come with giving a smart-home system permission to control a real computer.",
      },
    ],
    terms: standardTerms("QuantumOne"),
    privacy: standardPrivacy("QuantumOne"),
  },
  {
    id: 2,
    slug: "hassio-add-ons",
    title: "Hass.io Add-ons",
    description:
      "A personal collection of Hass.io / Home Assistant add-ons for extending a self-hosted smart-home setup with extra integrations and utilities.",
    tags: ["Shell", "Docker", "Home Assistant"],
    status: "shipped",
    year: "2019",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/hassio-addons",
    homepage: null,
    featured: true,
    highlight: false,
    summary:
      "Hass.io Add-ons packages self-hosted smart-home helpers into repeatable Home Assistant add-ons for a more capable local setup.",
    details: [
      {
        title: "What it solves",
        body: "Home Assistant becomes much more powerful when small services can be installed, updated, and tested consistently. This collection captures those extras as add-ons rather than one-off machine tweaks.",
      },
      {
        title: "How it is built",
        body: "The repository leans on Shell scripts and Docker packaging conventions, matching the Home Assistant add-on ecosystem. Each add-on is intended to be understandable, portable, and close enough to the platform's patterns to run on modest home hardware.",
      },
      {
        title: "Current direction",
        body: "The project is shipped and serves as a snapshot of a self-hosted home-automation setup. It is a practical base for anyone studying how Home Assistant add-ons are composed and maintained.",
      },
    ],
    terms: standardTerms("Hass.io Add-ons"),
    privacy: standardPrivacy("Hass.io Add-ons"),
  },
  {
    id: 3,
    slug: "codexero-db-plugin",
    title: "Codexero DB Plugin",
    description:
      "A database plugin written for Fedena, the open-source school management system, built to extend its data layer for a real school deployment.",
    tags: ["Fedena", "Plugin", "Education"],
    status: "archived",
    year: "2012",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/Codexero_DB_Plugin",
    homepage: null,
    featured: true,
    highlight: false,
    summary:
      "Codexero DB Plugin is an early education-tech artifact, built to adapt an open-source school system to the data needs of a real deployment.",
    details: [
      {
        title: "What it solves",
        body: "School management systems often need local customization once they meet real administrative workflows. This plugin explored a focused data-layer extension for Fedena, making a generic platform better suited to a particular school context.",
      },
      {
        title: "How it is built",
        body: "The project follows the plugin style of the Fedena ecosystem rather than trying to replace the host application. Its value is in the narrow integration work: fitting into an established education platform and extending the database behavior where the deployment needed it.",
      },
      {
        title: "Current direction",
        body: "The plugin is archived and best read as an early snapshot of practical software work around schools, databases, and local operational requirements.",
      },
    ],
    terms: standardTerms("Codexero DB Plugin"),
    privacy: standardPrivacy("Codexero DB Plugin"),
  },
  {
    id: 4,
    slug: "snips-for-hassio",
    title: "Snips for Hass.io",
    description:
      "A Home Assistant add-on packaging the Snips offline voice assistant for amd64 hardware, for hands-free home automation without sending audio to the cloud.",
    tags: ["Shell", "Snips", "Voice Assistant"],
    status: "archived",
    year: "2019",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/hassio-snips-amd64",
    homepage: null,
    featured: false,
    highlight: false,
    summary:
      "Snips for Hass.io brings an offline voice assistant into Home Assistant, emphasizing local control and private smart-home interaction.",
    details: [
      {
        title: "What it solves",
        body: "Voice control is convenient, but smart-home voice systems often depend on cloud processing. This add-on packaged Snips for Home Assistant so commands could be handled locally on amd64 hardware.",
      },
      {
        title: "How it is built",
        body: "The work centers on packaging, startup behavior, and integration boundaries. Shell and Home Assistant add-on conventions make the assistant installable inside the same self-hosted environment as the rest of the home automation stack.",
      },
      {
        title: "Current direction",
        body: "The project is archived, but it remains a useful reference for local voice-control architecture and privacy-minded smart-home experimentation.",
      },
    ],
    terms: standardTerms("Snips for Hass.io"),
    privacy: standardPrivacy("Snips for Hass.io"),
  },
  {
    id: 5,
    slug: "cxquotes",
    title: "cxquotes",
    description:
      "A small JavaScript tool for collecting and serving quotes, grown out of the Codexero blog's love of random ideas worth keeping around.",
    tags: ["JavaScript", "Web"],
    status: "archived",
    year: "2021",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/cxquotes",
    homepage: null,
    featured: false,
    highlight: false,
    summary:
      "cxquotes is a lightweight quote-collection tool, built around the simple pleasure of saving small lines that deserve to stay findable.",
    details: [
      {
        title: "What it solves",
        body: "A blog or personal site gathers fragments over time: quotes, little ideas, and lines that are too good to vanish into a notebook. cxquotes gives those fragments a small web-shaped home.",
      },
      {
        title: "How it is built",
        body: "The project uses JavaScript with a deliberately small surface area. Its appeal is in being direct: collect, store, and serve quotes without turning a tiny idea into an oversized platform.",
      },
      {
        title: "Current direction",
        body: "cxquotes is archived as a compact web experiment. It fits the workshop theme: a useful tool made because a personal workflow wanted one.",
      },
    ],
    terms: standardTerms("cxquotes"),
    privacy: standardPrivacy("cxquotes"),
  },
  {
    id: 6,
    slug: "tiktok-live-for-dart",
    title: "TikTok Live for Dart",
    description:
      "A Dart library for tapping into TikTok LIVE's realtime event stream - comments, gifts, and viewer activity - for building live-stream dashboards and bots.",
    tags: ["Dart", "Realtime", "TikTok API"],
    status: "archived",
    year: "2024",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/tiktoklive_dart2",
    homepage: null,
    featured: false,
    highlight: false,
    summary:
      "TikTok Live for Dart explores realtime stream events in Dart, making comments, gifts, and viewer activity available to apps and bots.",
    details: [
      {
        title: "What it solves",
        body: "Live-stream tooling often needs quick access to chat events and audience signals. This library turns those realtime events into data a Dart application can consume for dashboards, overlays, experiments, or moderation helpers.",
      },
      {
        title: "How it is built",
        body: "The project focuses on long-lived connection behavior, parsing event payloads, and representing TikTok LIVE activity in a Dart-friendly way. The useful work is in keeping the stream understandable while the upstream service stays dynamic.",
      },
      {
        title: "Current direction",
        body: "The library is archived, which is important for API-adjacent projects where external protocols can move quickly. It remains a reference for realtime client structure in Dart.",
      },
    ],
    terms: standardTerms("TikTok Live for Dart"),
    privacy: standardPrivacy("TikTok Live for Dart"),
  },
  {
    id: 7,
    slug: "issue-tracker",
    title: "Issue Tracker",
    description:
      "A Next.js and TypeScript practice build for tracking issues end-to-end, used to get hands dirty with the App Router and modern React patterns.",
    tags: ["TypeScript", "Next.js", "Learning"],
    status: "archived",
    year: "2024",
    stars: 0,
    forks: 0,
    url: "https://github.com/MoshRadix/issue-tracker",
    homepage: null,
    featured: false,
    highlight: false,
    summary:
      "Issue Tracker is a modern React practice project, using an ordinary product workflow to learn the shape of Next.js and TypeScript.",
    details: [
      {
        title: "What it solves",
        body: "Issue tracking is a familiar enough domain to reveal the real edges of an application: forms, status changes, lists, details, validation, and navigation. That makes it a strong practice ground for learning the App Router without inventing a strange product problem.",
      },
      {
        title: "How it is built",
        body: "The project uses Next.js and TypeScript, focusing on typed UI flows and the core patterns needed in day-to-day React work. It is less about being a commercial tracker and more about building fluency through a complete workflow.",
      },
      {
        title: "Current direction",
        body: "The repository is archived as a learning build. Its value is in showing the progression from tutorials into a hands-on, end-to-end application.",
      },
    ],
    terms: standardTerms("Issue Tracker"),
    privacy: standardPrivacy("Issue Tracker"),
  },
]

export const allProjectTags = [...new Set(projects.flatMap((project) => project.tags))]

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug)
}
